[package]
name = "cue-splatter"
version = "0.1.0"
edition = "2021"

[dependencies]
chardet = "0.2.4"
encoding = "0.2.33"
rayon = "1.10"
indicatif = { version = "0.17", features = ["rayon", "improved_unicode"] }
argh = "0.1"